export default {
  triggerType: 'click',
  requestTimeout: 1000,
  requestInterval: 1000,
  ajaxUrl: false,
  ajaxMethod: 'POST',
  ajaxAsync: true,
  ajaxUserName: null,
  ajaxPassword: null,
  ajaxContentType: 'application/x-www-form-urlencoded',
  ajaxTimeout: 30000,
  ajaxRequestHeaders: {'X-Requested-With': 'ajaxable'},
  ajaxData: {},
  ajaxBeforeSend: null,
  ajaxOnSuccess: null,
  ajaxOnError: null,
  ajaxOnComplete: null,
  ajaxOnAbort: null,
  ajaxOnTimeout: null,
  ajaxShowLoader: false,
  ajaxLoaderContainer: document.body,
  ajaxDoConfirm: false,
  domReplaceTo: false,
  domReplaceClosestTo: false,
  domReplaceInnerTo: false,
  domReplaceClosestInnerTo: false,
  domAppendTo: false,
  domPrepandTo: false,
  domClearTo: false,
  domClearClosestTo: false,
  domRemoveTo: false,
  domRemoveClosestTo: false,
  enableRedirect: true,
  enableReload: true,
  notificationType: 'alert', // toastr|alert|swal
  alertOptions: {},
  toastrOptions: {},
  swalOptions: {}
};
